### ISSUE TITLE
End User Registration 「使用者登记」

### ISSUE THREAD

**Issue by tomsun28** [dromara/sureness#64]
### Who is using sureness？  

Thank you very much for your attention and support to sureness. This is the biggest motivation for us to move forward.      

### The original intention of this issue

- Learn more about the practical use scenarios of sureness and listen to the community to make sureness better.    
- We want to attract more partners to contribute to sureness.  

### We look forward to your registration      

You can refer to the below:    

````
Organization: usthe
Location: chengdu, China
Contact: tomsun28@outlook.com
Purpose: Integrate existing gateways to protect api security
````

### Thanks again for your participation!    

sureness community  

---- 

### 谁在使用 sureness？

非常感谢大家对 sureness 的关注和支持，这是我们前进最大的动力。

### 这个 issue 的出发点

- 聆听社区的声音，了解实际使用场景，让 sureness 解决实际的问题
- 吸引更多的开发者参与和贡献

### 我们期待您的登记   
信息参考如下：
````
组织：usthe
地点：成都，中国
联系方式： tomsun28@outlook.com
使用场景：集成现有网关来对api进行安全保护
使用感受：xxxxx
````
### 多谢您的支持！
sureness 社区

**Comment by tomsun28** [comment]
组织：图逍遥科技      
地点：昆明，中国      
联系方式： gyckk@126.com      
使用场景：改造现有项目，替换shiro      
使用感受：已完成现有项目的替换工作，无缝切换，是我想要的      
登记信息来自[gitee](https://gitee.com/tomsun28/sureness/issues/I386R7#note_4778666)

**Comment by XJMongo** [comment]
组织：markableai
地点：杭州，中国
使用场景：权限系统，开发完成 尚未实际使用
使用感受：能在api级别添加认证鉴权感觉还是挺好用的

**Comment by tomsun28** [comment]
Organization: h3c
Location: chengdu, China
Contact: g17956@h3c.com
Purpose: Protect apm server http endpoints

**Comment by tomsun28** [comment]
Organization: TanCloud 探云 https://tancloud.cn https://hertzbeat.com
Location: mianyang, China
Contact: [tomsun28@outlook.com](mailto:tomsun28@outlook.com)
Purpose: Protect hertzbeat and tancloud http endpoints
