### ISSUE TITLE
请问如何在基于 graphql-java 的 GraphQL 实现中使用 sureness 库？

### ISSUE THREAD

**Issue by GoFly233** [dromara/sureness#94]
请问如何在基于 graphql-java 的 GraphQL 实现中使用 sureness 库？
服务器框架是用的 Ktor，感觉 sureness 似乎只能对 RESTful 进行保护

**Comment by tomsun28** [comment]
@GoFly233 hi 可以对graphql API保护，但不能对graphql里面的请求数据进行权限控制。如果需要对其请求数据权限控制，graphql官网建议是放到业务逻辑层即具体的后端API中 - https://graphql.cn/learn/authorization/ ， 我有一种思路不知道行不行供参考。
1. 对graphql关联的后端微服务API进行认证鉴权保护-一般这里使用统一网关
2. 在实现graphql请求数据对象对应的每个dataFetcher里，判断对应请求到的后端微服务API是否返回无权限（即403状态码），然后对graphql返回数据进行置空或者其它处理

**Comment by GoFly233** [comment]
> @GoFly233 hi 可以对graphql API保护，但不能对graphql里面的请求数据进行权限控制。如果需要对其请求数据权限控制，graphql官网建议是放到业务逻辑层即具体的后端API中 - https://graphql.cn/learn/authorization/ ， 我有一种思路不知道行不行供参考。
> 
> 1. 对graphql关联的后端微服务API进行认证鉴权保护-一般这里使用统一网关
> 2. 在实现graphql请求数据对象对应的每个dataFetcher里，判断对应请求到的后端微服务API是否返回无权限（即403状态码），然后对graphql返回数据进行置空或者其它处理

这边暂时不打算做微服务，但是还是感谢给了我一种思路
目前的想法就是在 Service 做鉴权，如果鉴权失败就直接抛出异常交给上层处理（即 GraphQL Resolves，View 层）
你看这样可信度大概如何？后端萌新，如果理解不到位还请多多指教

**Comment by tomsun28** [comment]
@GoFly233 可以试试，我看graphql官网建议也是放到业务逻辑层

**Comment by GoFly233** [comment]
> @GoFly233 可以试试，我看graphql官网建议也是放到业务逻辑层

那么

**Comment by GoFly233** [comment]
> @GoFly233 可以试试，我看graphql官网建议也是放到业务逻辑层

是指在业务逻辑层手动鉴权吗？那是不是不需要全局拦截器了？

**Comment by tomsun28** [comment]
不是，官网说的业务逻辑层我理解的是graphql后面的具体服务实现(即非graphql层)。可以按你说的service抛出，全局拦截权限异常处理试试

**Comment by tomsun28** [comment]
你好，请问这个还有问题吗  没有的话我关了哦

**Comment by GoFly233** [comment]
> 你好，请问这个还有问题吗  没有的话我关了哦

我来关吧，谢谢了
